spring.application.name=checkrr


#datasource
spring.profiles.active=dev
server.port=3001
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=validate


#flybase
spring.flyway.enabled=false

#sql commands
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

#logging
logging.level.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.tool.schema.spi=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.boot.autoconfigure.orm.jpa=DEBUG
#logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG




